<?php

namespace App\Models\User;

use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Str;
use Laravel\Sanctum\PersonalAccessToken;

class UserPersonalAccessToken extends PersonalAccessToken
{
    protected $table = 'personal_access_tokens';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'name',
        'token',
        'abilities',
        'expires_at',
        'two_fa_code',
        'two_fa_verified',
        'two_fa_expired_at',
        'related_access_token_id',
        'is_remember_me'
    ];

    protected $casts = [
        'abilities' => 'array',
        'last_used_at' => 'datetime',
        'expires_at' => 'datetime',
        'tokenable_id' => 'string',
    ];

    protected static function boot(): void
    {
        parent::boot();

        static::creating(function($model){
            if (empty($model->id)) {
                $model->id = Str::uuid();
            }
        });
    }

    public function tokenable(): MorphTo
    {
        return $this->morphTo('tokenable', 'tokenable_type', 'tokenable_id', 'id'); // TODO: Change the autogenerated stub
    }
}
